### ISSUE TITLE
PHP ^8.2  and Laravel 11 Support

### ISSUE THREAD

**Issue by WhiskeyM1ke** [luilliarcec/laravel-username-generator#3]
`Problem 1
    - luilliarcec/laravel-username-generator 1.0.0 requires php ^7.1 -> your php version (8.2.9) does not satisfy that requirement.
    - luilliarcec/laravel-username-generator[1.0.1, ..., 1.1.1] require php ^7.2 -> your php version (8.2.9) does not satisfy that requirement.
    - luilliarcec/laravel-username-generator[1.2.0, 2.0.0, ..., 2.2.0] require laravel/framework ^6.0|^7.0|^8.0 -> found laravel/framework[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require 
(^11.0).
    - luilliarcec/laravel-username-generator 3.0.0 requires laravel/framework ^9.0 -> found laravel/framework[v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.0).
    - luilliarcec/laravel-username-generator 4.0.0 requires laravel/framework ^10.0 -> found laravel/framework[v10.0.0, ..., v10.48.8] but it conflicts with your root composer.json require (^11.0).`

**Comment by luilliarcec** [comment]
You can open a PR with the changes to support PHP 8.2 and L11, don't forget to update the GitHub actions.

**Comment by luilliarcec** [comment]
Fix on V5
